package ExceptionHandling;

import java.util.*;

class CusException extends Exception{
	public CusException()
	{
		
	}
}
public class ExcepProject {

	void withdraw(int accbal)
	{
		System.out.println("enter amount to withdraw");
		Scanner sc = new Scanner(System.in);
		int wd=sc.nextInt();
		try {
			if(wd>accbal) {
				throw new CusException();
			}
			else {
				accbal=accbal-wd;
				System.out.println("withdrawl completed");
			}
		}
	}
	
	
	void deposite()
	{
		
	}
	
	void checkbal()
	{
		
	}
	
	public static void main(String args[])
	{
		int y;
		int accbal=10000;
		String userid = "12345678";
		String pswd = "12345";
		Scanner sc = new Scanner(System.in);
		System.out.println("Enter userid : ");
		String userid1 = sc.nextLine();
		System.out.println("Enter password : ");
		String pswd1 = sc.nextLine();
		ExcepProject obj=new ExcepProject();
		if(userid.equals(userid1) && pswd.equals(pswd1)) {
		//System.out.println("Both are equal");
			while(true) {
			System.out.println("Select any one option : \n 1.Withdraw \n 2.Deposit \n 3.Balance \n 4.Exit \n");
			y=sc.nextInt();
			if(y==1 || y==2 || y==3 || y==4) {
			switch(y)
			{
			case 1: obj.withdraw(accbal);
			case 2:obj.deposite();
			case 3:obj.checkbal();
			case 4: 
			
			
			}}
			
		}}
		else {
			System.out.println("Not matched..");
		}
	}
	
	
	
}
