import java.io.IOException;

public class Try_catch {
	public static void main(String[] args) {
		try
		{
	  int a=2,b=0,c;
	  c=2/0;
	}	
	catch(ArithmeticException e)
		{
  System.out.println("e");
	}

	}
}

